6-module
js-tasks-ru/jsbasic-20241021_isaevai pull request #6
Opened 2024-11-26 12:42 UTC by AlekseyIsaev89

1. Таблица с удаляемыми строками
2. Учебный проект: Карточка товара
3. Учебный проект: Карусель

2024-11-26 12:43 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-11-26 13:47 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-11-28 20:14 UTC, SinimaWath requested changes

2024-11-28 20:14 UTC, SinimaWath commented on 7-module/2-task/index.js
> +      this.modal.parentNode.removeChild(this.modal);
Сложно получается.

Чтобы удалить елемент со страницы: `this.modal.remove()`

2024-12-01 10:41 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-12-01 10:42 UTC, AlekseyIsaev89 commented on 7-module/2-task/index.js
> +      this.modal.parentNode.removeChild(this.modal);
7-module/2-task - внес корректировки.

2024-12-01 19:05 UTC, SinimaWath approved these changes

2024-12-01 19:07 UTC, merged